# Generated by Django 3.2.4 on 2022-07-05 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0004_auto_20220704_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('schedule_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_user.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_user.doctor')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_user.timeinterval')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_user.patient')),
            ],
        ),
    ]
